spring.application.name=RiderService
#server.port=8080
server.port=${PORT}

#spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.fxyguckdsauqyxstinyd&password=Gaya@1234
#spring.datasource.username=postgres.fxyguckdsauqyxstinyd
#spring.datasource.password=Gaya@1234
#spring.datasource.driver-class-name=org.postgresql.Driver


#spring.datasource.url=jdbc:postgresql://ep-raspy-dust-a4ocg293-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.url=${DB_URL}
#spring.datasource.username=neondb_owner
spring.datasource.username=${DB_USER}
#spring.datasource.password=npg_0AMT6GJohgIE
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# HikariCP Settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.connection-timeout=20000

# Flyway Configuration - Temporarily disabled
spring.flyway.enabled=false

#cloudinary.cloud-name=dvsmpntdf
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
#cloudinary.api-key=637365868341956
cloudinary.api-key=${CLOUDINARY_API_KEY}
#cloudinary.api-secret=MJz5bVWwclJNAbKc5_DC9qX9sL0
cloudinary.api-secret=${CLOUDINARY_API_SECRET}




# Temporarily use create-drop to recreate tables with correct UUID types
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# Email Configuration
#spring.mail.host=smtp.gmail.com
spring.mail.host=${EMAIL_HOST}
#spring.mail.port=587
spring.mail.port=${EMAIL_PORT}
#spring.mail.username=gayashankavishka2@gmail.com
spring.mail.username=${EMAIL_USERNAME}
#spring.mail.password=pvfo dluq gcis rzgr
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Jackson Configuration for DateTime handling
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false


#spring.grpc.server.port=9091
#spring.grpc.server.enabled=true

#spring.grpc.server.port=9091
#spring.grpc.server.enabled=true
#spring.grpc.server.keep-alive-time=30s
#spring.grpc.server.keep-alive-timeout=5s

#grpc.server.port=9091
#
#
#
#
#logging.level.net.devh.boot.grpc.server=DEBUG
#logging.level.io.grpc=DEBUG


#spring.grpc.server.keep-alive.time=30s
#spring.grpc.server.keep-alive.timeout=10s
#spring.grpc.server.permit-keep-alive-without-calls=true

#grpc.server.port=9091
grpc.server.port=${GRPC_SERVER_PORT}
grpc.server.security.enabled=false

logging.level.net.devh.boot.grpc.server=INFO
logging.level.io.grpc=INFO

grpc.client.user-service.address=static://localhost:8082


#spring.kafka.bootstrap-servers=10.20.11.67:9092
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.consumer.group-id=delivery-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.Map

#jwt.secret=rGqR2K44fudRka302KJicr4X9qB1r+uQ/tgYGNXYKKw=
jwt.secret=${JWT_SECRET}